console.log("Amar Dnyaneshwar Patil")
console.log("Hobbies- i love to explore about space, Love to play snooker, Love to go and travel alone")
console.log("Strength- I can adust in any situation and any surrounding, continuous lerner, I always focused towards work or anything what im doing")
console.log("Weaknesses- I hesitate to ask help, I'm bit introvert type of person, sometimes i get anger quickly because i want everything to be better.")
console.log("30+40 = 80")
console.log("49*479 = 23471")